project31_Django_Model_Form__/urls.py
from django.contrib import admin
from django.urls import path
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('display_topic/',display_topic,name='display_topic'),
    path('display_webpage/',display_webpage,name='display_webpage'),
    path('display_access_record/',display_access_record,name='display_access_record'),
]

app/models.py
from django.db import models
## Create your models here.

class Topic(models.Model):
    topic_name  = models.CharField(max_length=100, primary_key=True)

    def __str__(self):
        return self.topic_name

class Webpage(models.Model):
    topic_name  = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, primary_key=True)
    url = models.URLField()

    def __str__(self):
        return self.name

class Access_Record(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()
    author = models.CharField(max_length=100)

    def __str__(self):
        return self.author

app/forms.py
from django import forms
from app.models import *

class TopicModelForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = '__all__'

class WebpageModelForm(forms.ModelForm):
    class Meta:
        model = Webpage
        fields = '__all__'

class Access_RecordModelForm(forms.ModelForm):
    class Meta:
        model = Access_Record
        fields = '__all__'

app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from app.models import *
from app.forms import *

## Create your views here.


## For Topic
def display_topic(request):
    TMFO = TopicModelForm()
    d = {'TMFO':TMFO}

    if request.method == 'POST':
        TMFOD = TopicModelForm(request.POST)
        if TMFOD.is_valid():
            TMFOD.save()
            return HttpResponse("<center><h1 style='color:blue;'> Topic Data Inserted</h1></center>")
    return render(request, 'insert_topic.html',d)



## For Webpage
def display_webpage(request):
    WMFO = WebpageModelForm()
    d = {'WMFO':WMFO}

    if request.method == 'POST':
        WMFOD = WebpageModelForm(request.POST)
        if WMFOD.is_valid():
            WMFOD.save()
            return HttpResponse("<center><h1 style='color:blue;'> Webpage Data Inserted</h1></center>")
    return render(request, 'insert_webpage.html',d)




## For Access_Record
def display_access_record(request):
    ARMFO = Access_RecordModelForm()
    d = {'ARMFO':ARMFO}

    if request.method == 'POST':
        ARMFOD = Access_RecordModelForm(request.POST)
        if ARMFOD.is_valid():
            ARMFOD.save()
            return HttpResponse("<center><h1 style='color:blue;'> Access Record Data Inserted</h1></center>")
    return render(request, 'insert_access_record.html',d)

templates/insert_access_record.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            font-family: sans-serif;
            background: linear-gradient(90deg, rgba(10,201,77,1) 34%, rgba(0,112,255,1) 100%);
            font-size: 1.5em;
        }
        h1{
            color: black;
        }
        input[type="submit"]{
            border: none;
            font-size: .7em;
            padding: 10px 30px;
            border-radius: 15px;
            background-color: rgb(35, 151, 145);
            color: white;
            transition: .5s;
        }

        input{
            transition: .5s;
        }

        #id_name,#id_date,#id_author{
            font-size: .9em;
            width:70%;
        }
        .abc{
            width: fit-content;
            background-color: whitesmoke;
            border-radius: 20px;
            padding: 30px;
            /* box-shadow: -20px 20px 50px rgb(70, 67, 67); */
            box-shadow: 0 0 50px rgb(70, 67, 67);
        }
        
        .input{
            border: 1px solid black;
            border-radius: 20px;
            cursor: pointer;
        }
        input:hover{
            box-shadow: -5px 5px 25px black;
            border: none;
        }
        
        .input:hover{
            background-color: tomato;
            color: white;
        }
        
        
        .tus{
            height: 25px;
            border-radius: 5px;
            background-color: lightcyan;
        }
    </style>
</head>
<body>
    <center>
        <h1>Access Record Details</h1>
        <div class="abc">
            <form method="POST">
                {% csrf_token %}
                <table cellpadding="10">
                    <tr>
                        <td>{{ARMFO}}</td>
                    </tr>
                    <tr>
                        <td colspan="2" align="center"><input type="submit" value="submit" class="input"></td>
                    </tr>
                </table>
            </form>
        </div>

    </center>
</body>
</html>

templates/insert_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            font-family: sans-serif;
            background: linear-gradient(90deg, rgba(10,201,77,1) 34%, rgba(0,112,255,1) 100%);
            font-size: 1.5em;
        }
        h1{
            color: black;
        }
        input[type="submit"]{
            border: none;
            font-size: .7em;
            padding: 10px 30px;
            border-radius: 15px;
            background-color: rgb(35, 151, 145);
            color: white;
            transition: .5s;
        }

        input{
            transition: .5s;
        }

        #id_topic_name{
            font-size: .9em;
            width:70%;
        }
        .abc{
            width: fit-content;
            background-color: whitesmoke;
            border-radius: 20px;
            padding: 30px;
            /* box-shadow: -20px 20px 50px rgb(70, 67, 67); */
            box-shadow: 0 0 50px rgb(70, 67, 67);
        }
        
        .input{
            border: 1px solid black;
            border-radius: 20px;
            cursor: pointer;
        }
        input:hover{
            box-shadow: -5px 5px 25px black;
            border: none;
        }
        
        .input:hover{
            background-color: tomato;
            color: white;
        }
        
        
        .tus{
            height: 25px;
            border-radius: 5px;
            background-color: lightcyan;
        }
    </style>
</head>
<body>
    <center>
        <h1>Topic Details</h1>
        <div class="abc">
            <form method="POST">
                {% csrf_token %}
                <table cellpadding="10">
                    <tr>
                        <td>{{TMFO}}</td>
                    </tr>
                    <tr>
                        <td colspan="2" align="center"><input type="submit" value="submit" class="input"></td>
                    </tr>
                </table>
            </form>
        </div>

    </center>
</body>
</html>

templates/insert_webpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            font-family: sans-serif;
            background: linear-gradient(90deg, rgba(10,201,77,1) 34%, rgba(0,112,255,1) 100%);
            font-size: 1.5em;
        }
        h1{
            color: black;
        }
        input[type="submit"]{
            border: none;
            font-size: .7em;
            padding: 10px 30px;
            border-radius: 15px;
            background-color: rgb(35, 151, 145);
            color: white;
            transition: .5s;
        }

        input{
            transition: .5s;
        }

        #id_topic_name,#id_name, #id_url{
            font-size: .9em;
            width:70%;
        }
        .abc{
            width: fit-content;
            background-color: whitesmoke;
            border-radius: 20px;
            padding: 30px;
            /* box-shadow: -20px 20px 50px rgb(70, 67, 67); */
            box-shadow: 0 0 50px rgb(70, 67, 67);
        }
        
        .input{
            border: 1px solid black;
            border-radius: 20px;
            cursor: pointer;
        }
        input:hover{
            box-shadow: -5px 5px 25px black;
            border: none;
        }
        
        .input:hover{
            background-color: tomato;
            color: white;
        }
        
        
        .tus{
            height: 25px;
            border-radius: 5px;
            background-color: lightcyan;
        }
    </style>
</head>
<body>
    <center>
        <h1>Webpage Details</h1>
        <div class="abc">
            <form method="POST">
                {% csrf_token %}
                <table cellpadding="10">
                    <tr>
                        <td>{{WMFO}}</td>
                    </tr>
                    <tr>
                        <td colspan="2" align="center"><input type="submit" value="submit" class="input"></td>
                    </tr>
                </table>
            </form>
        </div>

    </center>
</body>
</html>